### PR TITLE
BUG: keep proper array shape even if n_samples=1

### PR DESCRIPTION
**Pull request by Visdoom**
#25

### CODE REVIEW

**Comment by jseabold** [comment]
Do you mind adding a test for this corner case?

**Comment by Visdoom** [comment]
Sorry for the noob question but I am not entirely sure, how. Which class would I put it in? 
What should be tested?

**Comment by wlattner** [comment]
No worries. I think a test asserting that `predict_proba` works when `x` is a column vector is sufficient.  See [`glmnet/tests/test_logistic.py`](https://github.com/civisanalytics/python-glmnet/blob/f7f2cc2e0552c136667b84ed55cb2f5434a62219/glmnet/tests/test_logistic.py#L75) for an example.

We're currently using [nose](http://nose.readthedocs.io/en/latest/) to run the tests:
```bash
nosetests -v
```

**Comment by stephen-hoover** [comment]
This is fixed in PR #51 .

**Pull request closed without merging**
